name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install .NET Framework 4.6 Developer Pack
      run: choco install netfx-4.6-devpack -y
    - uses: microsoft/setup-msbuild@v1.1
    - name: Build VSIX Project
      run: msbuild VSCopyLocal\VSCopyLocal.VSPackage.csproj /p:Configuration=Release

    # [Optional] Run tests only if you have standard .NET test projects
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
